### ISSUE TITLE
Cannot provide enter choice options for "Select One Response" and "Select Many Response" blocks

### ISSUE THREAD

**Issue by Calebbubune** [FLOIP/flow-builder#227] opened 2022-04-22 12:35 UTC
**What I did**
* Added the blocks: "Select One Response" or "Select Many Response"  to the flow builder
* Tried to enter choice options for either of the blocks

**Expectation**
* User should be able to add choice options for the blocks

What happened 
* The user could not add choice options to the either of the blocks

On master, the choice options do not function properly -- each letter entered is set as a new choice option.

**Comment by safydy-r** [comment] 2022-04-22 20:59
@Calebbubune , I think this is a duplicate of https://viamoinc.atlassian.net/browse/VMO-5817, right ?

**Comment by Calebbubune** [comment] 2022-04-22 22:18
@safydy-r since the issue in https://viamoinc.atlassian.net/browse/VMO-5817 is related to what I have reported earlier, I will close the issue reported here.

**Closed** 2022-04-22 22:18 UTC
